services:
  iris:
    build: 
      context: .
    restart: always
    container_name: ${iris_container_name}
    hostname: ${iris_container_name}
    ports:
      - 1972
      - 52773
      - 53773
    command: --check-caps false
    volumes:
      - ./data:/data



